pipeline {
    agent any
    
    options {
        disableConcurrentBuilds()
    }
    
    tools {
        nodejs 'NodeJS-20'
    }
    
    environment {
        SONAR_TOKEN = credentials('sonarqube-token')
        SONAR_HOST_URL = 'http://bookshop-sonarqube:9000'
        SONAR_SCANNER_HOME = tool 'SonarScanner'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm ci'
                }
            }
        }
        
        stage('Build') {
            steps {
                dir('frontend') {
                    sh 'npm run build'
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('frontend') {
                    sh 'npm test -- --watch=false --browsers=ChromeHeadless --code-coverage'
                }
            }
            post {
                always {
                    publishHTML([
                        reportDir: 'frontend/coverage',
                        reportFiles: 'index.html',
                        reportName: 'Coverage Report'
                    ])
                }
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                dir('frontend') {
                    sh '''
                        ${SONAR_SCANNER_HOME}/bin/sonar-scanner \\
                          -Dsonar.projectKey=bookshop-frontend \\
                          -Dsonar.sources=src \\
                          -Dsonar.exclusions=**/node_modules/**,**/dist/** \\
                          -Dsonar.tests=src \\
                          -Dsonar.test.inclusions=**/*.spec.ts \\
                          -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info \\
                          -Dsonar.host.url=${SONAR_HOST_URL} \\
                          -Dsonar.login=${SONAR_TOKEN}
                    '''
                }
            }
        }
        
        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
    
    post {
        failure {
            echo 'Pipeline failed!'
        }
        success {
            echo 'Pipeline succeeded!'
        }
    }
}
