# Configuración de SonarCloud para el Frontend
sonar.projectKey=cavalenzuela_bookshop-app-frontend
sonar.organization=cavalenzuela
sonar.host.url=https://sonarcloud.io

# Exclusiones de archivos para evitar "ruido" en las métricas
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/coverage/**,**/*.spec.ts,**/assets/**,**/environments/**,**/main.ts,**/polyfills.ts,**/test.ts,**/*.module.ts,**/*.config.ts

# Configuración de cobertura
sonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info
sonar.typescript.lcov.reportPaths=frontend/coverage/frontend/lcov.info

# Fuentes y tests
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
