spring:
  application:
    name: bookshop
  datasource:
    driver-class-name: org.postgresql.Driver
  threads:
    virtual:
      enabled: true

server:
  port: 8282

# Configuración de SpringDoc OpenAPI (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
  show-actuator: false

# Configuración de Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized
